name: Convert Live PHP Stream to M3U8

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Capture live stream and convert to HLS
        run: |
          mkdir hls_output
          ffmpeg -i "https://8088y.site/P/X/Box.php?id=18456" \
            -c:v copy -c:a copy \
            -f hls -hls_time 6 -hls_list_size 10 -hls_flags delete_segments \
            hls_output/stream.m3u8

      - name: Upload HLS Output
        uses: actions/upload-artifact@v3
        with:
          name: hls-stream
          path: hls_output
